### ISSUE TITLE
Promoters can't add new collaborators

### ISSUE THREAD

**Issue by hampelm** [postcode/senoia#114]
Clicking on the "Add users" button as a Promoter displays a popup that has column headings but no users. It might be good to add a note like "No users with access" for clarity.

Clicking the "Add Collaborator" button doesn't result in any visible action. Looking at the network console, I see a request for `/update_user_plan`, which is not a valid route.

![screen shot 2016-01-20 at 4 33 50 pm](https://cloud.githubusercontent.com/assets/86435/12463887/20adde40-bf94-11e5-998f-40029f8516e5.png)

**Comment by andyhull** [comment]
This appears to be fixed. Could have been related to the permissions issue.
