### ISSUE TITLE
Update users page to support associations with organizations

### ISSUE THREAD

**Issue by ttmp** [postcode/senoia#165]
We need to create organizations (e.g. AMR, Rock, Rec & Parks) and then be able to associate users with that department. Open to how this works (e.g. like Departments + Users in NextRequest).

The data structure is going to be
Agency: general address, email & phone number

**Comment by andyhull** [comment]
@ttmp are all the organizations a user could be part of represented by Promoters, Permitters, and Providers?

**Comment by ttmp** [comment]
Those are the organization types, though see #185 for the current naming conventions.

Obviously there are many more organizations, with a few examples as named above.
