### ISSUE TITLE
Create a page for a staff contact list

### ISSUE THREAD

**Issue by ttmp** [postcode/senoia#169]
They would need to submit this at least one week prior to the event date, but they would have the option to submit it even with the initial submission.
- Communications
- Event Coordinator
- Event Supervisor onsite
- Dispatch supervisor [onsite]
- Medical group supervisor [onsite]
- Triage supervisor [onsite]
- Transport supervisor [onsite]
- Non-transport supervisor [onsite]

Name
Organization (provider)
Contact number for the day of the event
Email

Options are: N/A (for small events), TBD, and entered

Will there be a unified command?
If yes, provide a list (even for big events this info doesn't get provided until week of)
By the week before the event, this would also include contact info for each of the listed assets.
The info we'd need is what was in the mockups.

**Comment by ttmp** [comment]
We've now separated out info for the specific assets into #223.

Only information for the bulleted contacts _must_ be collected by a week before (if not n/a).

**Comment by andyhull** [comment]
@ttmp did we ever get a mockup of this?

**Comment by andyhull** [comment]
@ttmp what does `Communications` mean in the first bullet?

**Comment by andyhull** [comment]
@ttmp I’m also not sure what `Options are: N/A (for small events), TBD, and entered` means
