### ISSUE TITLE
Add a new Venue (or Location) field

### ISSUE THREAD

**Issue by ttmp** [postcode/senoia#183]
This will be required for every plan since Aram wants to be able to search on it.

Dropdown list of nested locations
e.g. Golden Gate Park: Hellman Hollow
UI: maybe a dropdown list with typeahead; ability to select Other and then type in the location.
Aram will need to be able to edit this list of locations or reclassify the location

It seems like this is going to be dozens and dozens of places.

**Comment by andyhull** [comment]
These are just generic place names that Aram would use to identify different events?

**Comment by ttmp** [comment]
Yes. I was trying to pin him down on what he meant by venues, but he was vague. One example is various areas of Golden Gate Park, but he also said that any intersection could be considered a "venue". I warned that this could get really long and unwieldy over time.

It's definitely a list that he would be adding to and updating. Not sure how the app would handle it if a particular venue was assigned to a set of events and then he went to delete or change that later.
