### ISSUE TITLE
Develop a printable view for a Plan

### ISSUE THREAD

**Issue by ttmp** [postcode/senoia#184]
The components/formatting of this are:
- EMS plan template (one sheet)
- Map
- Communications list
  Note that there may need to be a new page for every operational period since staffing levels and locations will be different.

If they've uploaded additional documents (voucher, certificate, add'l map, etc.), those should be bundled as part of the download. If this can't be all one PDF, then maybe a ZIP file with multiple PDFs?

**Comment by andyhull** [comment]
@ttmp I’m not going to be able to get the maps printable by Thursday. It is actually pretty complicated to print out these google maps. Is there anything else holding this up?

**Comment by andyhull** [comment]
@hampelm I’m going to kick this over to you. The basic print layout is good, but we need to add the map. Maybe you can work on that?

**Comment by hampelm** [comment]
I'll get that going.
