### ISSUE TITLE
Display assets on the map once the asset is saved

### ISSUE THREAD

**Issue by ttmp** [postcode/senoia#195]
Right now they don't display until the whole plan is saved.

**Comment by andyhull** [comment]
@ttmp the way this is currently setup we need a reload to update the map and add the asset location to the asset. We would have to ajax this up.

**Comment by ttmp** [comment]
Okay, we can make this a July launch goal, though if we can do it sooner rather than later, that would be good. Like, after the training, we can still work on some stuff.
