### ISSUE TITLE
Add an Other option for assets

### ISSUE THREAD

**Issue by ttmp** [postcode/senoia#201]
This will allow them to enter a provider not in the dropdown.

Other is NOT an option for Transport.

**Comment by andyhull** [comment]
@ttmp there should be an “other” option in the provider dropdown? We will have to add a new provider that is just named “other”. Not sure how useful this would be to anyone, but it is easily done.

**Comment by ttmp** [comment]
See #202. The idea is that the workflow works one of two ways:

They pick Other and only then do the contact info fields appear. [preferred]
OR
If they pick an approved provider the contact info fields populate automatically, and if they pick Other then they need to enter this info manually.
