### ISSUE TITLE
Submit button is not appearing for a plan with revisions requested

### ISSUE THREAD

**Issue by ttmp** [postcode/senoia#208]
When the plan author is responding to revisions the only option at the bottom is to Save Draft (no Submit option).

**Comment by andyhull** [comment]
@ttmp  Right, they can only save the plan not move it on to the next stage, which is Approved. The idea is that authors respond to comments and fix items in the plan. Once Aram is satisfied then he can resolve all the comments and approve the plan.

**Comment by ttmp** [comment]
@andyhull Ah, it sound like this was a miscommunication between us then. It's really important for people to know whose court a plan is in. So when someone is responding to Revisions Requested they do need to be able to Save Draft (the way they would with a new plan before submitting), but once they think they have addressed all of his concerns they need to be able to Submit, which will move the stage back to Under Review and will send a notification out to Aram that it is once again ready for his review.

If people are just saving incremental changes to a draft it won't really be clear to Aram when they're just sort of working on something and when he is expected to review the changes.
