### ISSUE TITLE
Create a way to administer an approval notification list

### ISSUE THREAD

**Issue by ttmp** [postcode/senoia#216]
Aram needs to be able to create and administer a list of people across agencies & providers who get approval emails. This could be similar to how departments/organizations are managed.

**Comment by ttmp** [comment]
This is a group of people who get notifications for ALL plan approvals. They may or may not be associated with a specific plan.

**Comment by ttmp** [comment]
The name for this is Special Events Approval Notification Group.

**Comment by andyhull** [comment]
Here is the list.
[Special Event Plan Approval Notification Group.txt](https://github.com/postcode/senoia/files/182245/Special.Event.Plan.Approval.Notification.Group.txt)
