### ISSUE TITLE
Dates are not being saved correctly in the database

### ISSUE THREAD

**Issue by ttmp** [postcode/senoia#290]
And this impacts the calendar.

For instance, Aram saved Lagoon to Surf as particular time 5/15/16 6am to 6pm, but on the All Plans page it is showing as 5/14/16 5pm to 5pm, and on the calendar it is showing up as the 14th.

Weirdly, though, on the All Events page the date filters seem to find the event as if it's on the 15th.

**Comment by andyhull** [comment]
@ttmp this looks like it is a display problem not a problem with saving to the DB.

**Comment by ttmp** [comment]
@andyhull Okay, that makes sense given that the filters seem to be working on the real dates. That said, this is a high priority bug since users aren't able to see correct info for their events & operational periods.
