### ISSUE TITLE
Add Total Crowd Estimate field

### ISSUE THREAD

**Issue by ttmp** [postcode/senoia#293]
Helper text: Number of people in attendance over the entire operational period.

**Comment by ttmp** [comment]
I'd say this is a high priority because Aram wants this in the app, so I should be able to show it at the demo tomorrow and explain it.

That said, this is a super last-minute addition, so of the high priority issues, it's fine if this one comes last.

**Comment by andyhull** [comment]
@ttmp this is the total across all the operation periods, correct?

**Comment by ttmp** [comment]
No this is still for a single operational period.

It's like, maybe there's an event on day and at the peak time there are
4,000 people there simultaneously, but over the course of the operational
period 10,000 will have been there at some point.
ᐧ

On Wed, Mar 30, 2016 at 12:43 PM, Andy Hull notifications@github.com
wrote:

> @ttmp https://github.com/ttmp this is the total across all the
> operation periods, correct?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/postcode/senoia/issues/293#issuecomment-203603235

## 

Tamara Manik-Perlman
CEO & Founder, NextRequest http://nextrequest.com
@TamaraMP http://twitter.com/TamaraMP
NextRequest makes public records better for government and the public.
ᐧ
