### ISSUE TITLE
Notifications don't seem to be going out

### ISSUE THREAD

**Issue by ttmp** [postcode/senoia#295]
Revision requested notification: email to plan creator and admin
Plan resubmitted: "
Plan approved: the whole shebang

**Comment by andyhull** [comment]
@ttmp I just tested this on staging and I received emails for:
plan submitted
plan needs revision
plan needs review
plan approved

These all went to the creator and collaborators.

**Comment by ttmp** [comment]
I will go through and test this myself, but when we were running through creating http://sfdemmedicalplans.com/plans/3 Aram said he was getting some notifications but not others.
