### ISSUE TITLE
All comments need to be visible to the admin even on approved plans

### ISSUE THREAD

**Issue by ttmp** [postcode/senoia#296]
Currently only some of them seem to be showing.

**Comment by andyhull** [comment]
@ttmp only admins should see comments on approved plans?

**Comment by ttmp** [comment]
@andyhull On an approved plan the admin and the plan author, collaborators, staff, etc. should be able to see the comments, but I don't think these should be visible to the public at large.

This issue is about the fact that on an approved plan when Aram was logged in as an admin some of the comments were showing up, but he had made more (resolved) comments on the individual assets that were no longer showing up. This was http://sfdemmedicalplans.com/plans/3

If you log in as an admin there's the ability to show the resolved comments for the Add Supplementary Documents section, but not for any of the other sections.
