### ISSUE TITLE
Datetime is broken on the PETR page

### ISSUE THREAD

**Issue by ttmp** [postcode/senoia#306]
Again, not saving times correctly. Doesn't seem to be just a timezone error, since Aram entered 5/15 10:45am but it saved as 5/15 5pm.

**Comment by andyhull** [comment]
@ttmp do you mean the date display on the PETR?

**Comment by ttmp** [comment]
Not sure I understand the question. Date and times are again not being saved correctly, as on the main Plan page.

**Comment by andyhull** [comment]
@ttmp I don’t see a spot to enter dates on the PETR, but I do see them displayed.

**Comment by ttmp** [comment]
@andyhull They enter a date & time for Time Patient Transported Off-site
