### ISSUE TITLE
Fix Admin View

### ISSUE THREAD

**Issue by andyhull** [postcode/senoia#44]
When logged in as an admin I cannot see the comments or request revision buttons. I may have messed this up when merging everything into master.

**Comment by villesundberg** [comment]
Request revision button fixed in be294f2b8bfd7ae113300bb6506bc3aaba30fe24.

Currently, comments are only visible when the plan is past the "draft" state. Should we change it so that users can comment on a draft before it's submitted?

**Comment by andyhull** [comment]
Yes that is correct. Users can only comment on a plan after it is out of the draft state.

**Comment by villesundberg** [comment]
Can you see the comments when you're logged in as an admin when the plan is at "awaiting_review" or "being_reviewed"? It works for me right now.
