### ISSUE TITLE
Send Providers a Confirmation Email When Added to a Plan

### ISSUE THREAD

**Issue by andyhull** [postcode/senoia#47]
When a new provider is added to a plan they should be sent an email to confirm that they are participating in the event. In the email, providers will click a link to confirm that they are participating in the event, which will be indicated within the plan. This is mocked up in SF DEM v1.pdf on the last page.

**Comment by villesundberg** [comment]
<img width="821" alt="screenshot 2015-09-16 13 21 02" src="https://cloud.githubusercontent.com/assets/372604/9903373/41628766-5c76-11e5-9564-142f6319d0b2.png">
