### ISSUE TITLE
Add Overall Plan Map

### ISSUE THREAD

**Issue by andyhull** [postcode/senoia#8]
All assets with locations should be plotted on one master interactive map on the plan page.

**Comment by hampelm** [comment]
@andyhull Should I assign this to myself?

**Comment by hampelm** [comment]
Question about the mockup: how literal are the labels? For example the mock shows first aid w/nurse, EMT, MD separately. Do we need to distinguish those? It imagine those won't be discrete -- eg some stations will have a nurse and an MD.

![screen shot 2016-01-22 at 2 39 27 pm](https://cloud.githubusercontent.com/assets/86435/12521019/fd17b108-c115-11e5-8776-61ac5c9862e6.png)

**Comment by hampelm** [comment]
Also, do you want icons or the standard map markers? I can dig around noun project and adapt some, or just use the standards: 

![screen shot 2016-01-22 at 4 37 21 pm](https://cloud.githubusercontent.com/assets/86435/12523692/6f597462-c126-11e5-80dd-51af02ee9fb3.png)

**Comment by andyhull** [comment]
The standard ones are fine.

-- 
Andy

On January 22, 2016 at 4:37:36 PM, Matt Hampel (notifications@github.com) wrote:

Also, do you want icons or the standard map markers? I can dig around noun project and adapt some, or just use the standards:
