### ISSUE TITLE
Include plan author on PETR notifications

### ISSUE THREAD

**Issue by ttmp** [postcode/senoia#98]
Producers would like to get the reminders about these even if a provider has been designated to complete these. Could help them make sure people are on task.

**Comment by andyhull** [comment]
@ttmp what are PETR notifications?

**Comment by andyhull** [comment]
@ttmp still not sure what this means.

**Comment by ttmp** [comment]
@andyhull Sorry, Post-Event Treatment Report

**Comment by andyhull** [comment]
@ttmp I don’t think we are sending reminders about this. When would these go out?

**Comment by ttmp** [comment]
So after the event is complete the event producer/plan creator and the person designated to do the PETR should receive email notifications that they need to complete this. These have to be submitted within 14 days, so send one after 7 days and one at 14 days. 

It should be something along the lines of,

> The Post-Event Treatment Report for {{Event Name}} on {{Event Date}} must be received by {{Due Date = 14 days after event date}}. Failure to submit this report may affect the approval of future event plans.

**Comment by ttmp** [comment]
As we discussed in Slack, Admins, the plan creator and the submitter should all receive notifications when this has been completed and submitted.
